### ISSUE TITLE
Failing to link on MacOS

### ISSUE THREAD

**Issue by KevinCybura** [shadeMe/liblinear-rs#4]
When trying to add liblinear-rs as a dependecy to my rust project I am getting this error
```
error: linking with `cc` failed: exit code: 1
...
  = note: ld: library not found for -lstdc++
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
This seems to be because I am compiling on a mac it seems like stdc++ has been deprecated
https://stackoverflow.com/questions/51060596/ld-library-not-found-for-lstdc-6

**Comment by shadeMe** [comment]
Thanks for the report. Will investigate soon.

**Comment by shadeMe** [comment]
@KevinCybura Sorry about the delay - Been rather busy. Could you please try to rebuild after commenting out [line 6 in `build.rs`](https://github.com/shadeMe/liblinear-rs/blob/c96e67d7826e8a4d8a5dc64056271483769b227f/build.rs#L6)? I personally can't test it as I develop on Linux/Windows.

According to the `cc` crate's [docs](https://docs.rs/cc/1.0.4/cc/struct.Build.html#method.cpp_link_stdlib), the default value will automatically be selected depending on the target platform.

**Comment by shadeMe** [comment]
[v1.0.0](https://github.com/shadeMe/liblinear-rs/releases/tag/v1.0.0) should hopefully fix this issue.
